### ISSUE TITLE
Spaces in the query string are encoded as `%20` instead of `+`

### ISSUE THREAD

**Issue by balazsbotond** [balazsbotond/urlcat#1]
Input:

```
urlcat('http://example.com', '/path', { q: 'a b' })
```

Expected:

```
http://example.com/path?q=a+b
```

Actual:

```
http://example.com/path?a%20b
```

**Comment by flxwu** [comment]
Hey,

so actually in some use cases (like OAuth1) we require whitespaces to be encoded as %20, instead of +.

Can you thus please add an option to encode it as %20? 

Thanks :)
