### ISSUE TITLE
Query params output

### ISSUE THREAD

**Issue by Saafine** [balazsbotond/urlcat#103]
**Describe the bug**
Possibly incorrect queryParams output

**To Reproduce**
urlcat('https://google.com', '', {test: 'abc'}) 
returns https://google.com/test=abc

**Expected behavior**
Should return
https://google.com?test=abc

**Comment by harshilparmar** [comment]
Hey @balazsbotond Can I help for this?

**Comment by balazsbotond** [comment]
@Saafine thank you for the bug report.

I've successfully reproduced it using the currently published npm version and it is indeed a problem.

**Comment by balazsbotond** [comment]
@harshilparmar thanks, that would be great. I have a lot of work to do these days so I'm glad you showed up.

As a first step, we need to reproduce the bug on both `2.x` and the `master` branch - let's see which version it affects. Can you help with this first? After that, let's discuss the results here and decide how to proceed.

**Comment by harshilparmar** [comment]
> As a first step, we need to reproduce the bug on both `2.x` and the `master` branch - let's see which version it affects. Can you help with this first? After that, let's discuss the results here and decide how to proceed.

@balazsbotond Yeah sure, I will let you know!!

**Comment by harshilparmar** [comment]
@balazsbotond brother, this issue affects in both `2.x` and `master`. 
Observation : I think urlcat second param takes empty string in consideration.

**Comment by balazsbotond** [comment]
@harshilparmar thank you! I'm sorry it took this long to reply. If you still have the time, I'd be very thankful if you could work on a fix.

**Comment by harshilparmar** [comment]
@balazsbotond I am on it 👨‍💻

**Comment by balazsbotond** [comment]
@harshilparmar if you have time, could you backport the fix to the `2.x` branch and send another PR against that branch? This way I could release a new patch release after merging it and the latest published version would be free of known bugs.

**Comment by harshilparmar** [comment]
> 
> 
> @harshilparmar if you have time, could you backport the fix to the `2.x` branch and send another PR against that branch? This way I could release a new patch release after merging it and the latest published version would be free of known bugs.

Sure brother 👍🏼

**Comment by harshilparmar** [comment]
@balazsbotond Can you please close this issue? It might take time for new contributors.

**Comment by balazsbotond** [comment]
Closing because I decided to delete the `2.x` branch and concentrate on maintaining the currently published version.

**Comment by harshilparmar** [comment]
> Closing because I decided to delete the `2.x` branch and concentrate on maintaining the currently published version.

Really happy to see you back here ☺️

**Comment by balazsbotond** [comment]
@harshilparmar nice to see you again too :)
