### ISSUE TITLE
Proofread English text in the README and JSDoc

### ISSUE THREAD

**Issue by balazsbotond** [balazsbotond/urlcat#11]
I'm not a native English speaker. I would be very glad if someone from an English-speaking country could review the README and the JSDoc comments and correct any spelling/grammatic/stylistic mistakes.

**Comment by praveen5959** [comment]
I can work on this and raise a PR. If that's okay?

**Comment by balazsbotond** [comment]
@praveen5959 sure, thank you!

**Comment by praveen5959** [comment]
I have made the changes and raised a PR
https://github.com/balazsbotond/urlcat/pull/23 

Can you check and lemme know if any further changes required.
