### ISSUE TITLE
Don’t allow missing, null or undefined path parameters

### ISSUE THREAD

**Issue by balazsbotond** [balazsbotond/urlcat#13]
We should throw an `Error` instead of silently continuing and leaving the path parameter placeholder in the rendered path.

**Comment by harshilparmar** [comment]
@balazsbotond you are right 👍

**Comment by harshilparmar** [comment]
@balazsbotond  I have done this,I will do pr in #12

**Comment by balazsbotond** [comment]
@harshilparmar I've just released a new version (v2.0.3) which means your work is now live! 🎉

**Comment by harshilparmar** [comment]
@balazsbotond Ohh great 🥳 🎉
