### ISSUE TITLE
about release schedule

### ISSUE THREAD

**Issue by airtoxin** [balazsbotond/urlcat#134]
I want to use feature added on https://github.com/balazsbotond/urlcat/issues/6.
It merged Oct 3 last year but not released yet.
There are any release schedule?

**Comment by flxwu** [comment]
Hi, any update here? I need this feature too.

**Comment by mehdihaddad** [comment]
@balazsbotond @harshilparmar etc... ??? need you.

**Comment by harshilparmar** [comment]
The only @balazsbotond  can help here !! Don't know about a release schedule 😞

**Comment by mehdihaddad** [comment]
2 months with no answer... The project is already dead ? If someone can contact him...

**Comment by dreamerblue** [comment]
Hey, you can try `urlcat-fork` package from npm. I am now using this package to fix array format.

**Comment by harshilparmar** [comment]
> 2 months with no answer... The project is already dead ? If someone can contact him...

I already tried it already !! @balazsbotond Hey, Are you there!!

**Comment by balazsbotond** [comment]
I'm sorry it took so long but I have finally released the new version.
