### ISSUE TITLE
README diagram hard to read on GitHub's dark mode

### ISSUE THREAD

**Issue by knpwrs** [balazsbotond/urlcat#143]
See screenshot:

![image](https://user-images.githubusercontent.com/174864/110166693-55b13d00-7dba-11eb-82dc-cd9983a67fae.png)

**Comment by balazsbotond** [comment]
Thank for reporting this.

Looks like GitHub supports displaying a different image on dark mode: https://www.stefanjudis.com/notes/how-to-define-dark-light-mode-images-in-github-markdown/

The SVG is in the `docs/` folder, we could make a version with white text instead of black.

**Comment by balazsbotond** [comment]
Fixed.
