### ISSUE TITLE
Not compatible with Safari 10

### ISSUE THREAD

**Issue by comatory** [balazsbotond/urlcat#145]
**Describe the bug**
The path is incorrectly concatenated with stringified object.

**To Reproduce**

1. Use Safari 10
2. Navigate to [http://incandescent-farmer.surge.sh/](http://incandescent-farmer.surge.sh/)
3. Result is `/hello/world?%5Bobject=Object%5D=`

**Expected behavior**
Result should be `/hello/world` only

**Screenshots**
<img width="982" alt="Screenshot 2021-03-07 at 17 53 07" src="https://user-images.githubusercontent.com/5990424/110247735-0449af00-7f6e-11eb-816e-5868be75eb0a.png">

**Desktop (please complete the following information):**
 - OS: macOS Sierra
 - Safari
 - 10.1.2

**Comment by comatory** [comment]
Useful library that I've used in the past. I have built my own parsers like this before and did not want to do it again. My current project is Javascript SPA that supports ES6. So I was bummed seeing this in Safari 10 which is perfectly capable of running my code. However basically the app is unusable since I'm using `urlcat` to construct URLs for my application router and data fetching, so basically everything fails because this string is being injected as query parameter everywhere (at least it looks like it).

**Comment by Anricx** [comment]
any update?

**Comment by alfianandinugraha** [comment]
Can this issue fix by Babel?

**Comment by balazsbotond** [comment]
I've just merged the PR, sorry for the huge delay everyone.
