### ISSUE TITLE
Can not create url with # Eg: http://example.com/id/1234?foo=bar&bar=one&bar=two&bar=three#/api/groupId/34444

### ISSUE THREAD

**Issue by niroshana1234** [balazsbotond/urlcat#150]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by harshilparmar** [comment]
It would be nice to handle # url. What you say @balazsbotond 🤔

**Comment by balazsbotond** [comment]
If you don't use the issue template, please at least don't leave it in the description unchanged.

I'm sorry but supporting fragments is out of scope for this project.
