### ISSUE TITLE
Arrays as parameters

### ISSUE THREAD

**Issue by tema3210** [balazsbotond/urlcat#188]
**Is your feature request related to a problem? Please describe.**
Case: need multiple values for query parameter. Currently (urlcat = 2.0.4) it always turns an array into a string and that ends up being a query parameter.

**Describe the solution you'd like**
In that case query parameter should be mentioned multiple times: each time with another value from an array.

**Describe alternatives you've considered**
Back to handwriting query.

**Comment by balazsbotond** [comment]
Hi @tema3210, I've just released v3.0.0 - please check if the new version (which now includes qs, and can handle arrays/objects as parameters) solves you problem! I'm closing this issue now but feel free to reopen/comment if the version upgrade doesn't work out.
