### ISSUE TITLE
The inclusion of qs feels like a step backwards

### ISSUE THREAD

**Issue by wescopeland** [balazsbotond/urlcat#216]
Hi there,

I'm a longtime user of urlcat. Currently using it on many personal projects as well as at work where we see tens of thousands of uniques per day.

I recently updated to the latest version of urlcat, and I was really disappointed to see that the bundle size has increased so much. Previously, one of the things I loved about urlcat was its small footprint and how lightweight it was. But now, with the increase to 10Kb, it feels like a step backwards.

I understand that sometimes it's necessary to increase the size of a library in order to add new features or improve performance. But in this case, it's not clear to me why the bundle size had to increase so much. Could you please explain the reasoning behind this decision?

I'm also concerned about the impact this will have on the performance of my app. A larger bundle size means longer load times and potentially slower runtime performance. Is there anything being done to mitigate these potential negative effects?

Overall, I'm really disappointed with this change. I've been a big fan of urlcat for a long time, but this increase in bundle size feels like a step in the wrong direction. I hope that in future updates, the focus can be on keeping the library lightweight and efficient, while still adding new features and improvements.

Thank you for your time.

**Comment by balazsbotond** [comment]
Hi @wescopeland, thanks for the feedback!

While I appreciate the concern about bundle size in general, I don't think 1 vs 10 kB matters in any but the most extreme cases.

The motivation for using qs is explained in these issues:
- https://github.com/balazsbotond/urlcat/issues/6
- https://github.com/balazsbotond/urlcat/issues/5

I don't think reverting a new major version is in any case acceptable for an open source project. The decision to use qs has been made a long time ago and in my opinion it was a good one.

2.x will still be actively maintained. I will publish new releases if bugs are reported, so you can use v2 if you need a more streamlined and efficient library.

**Comment by wescopeland** [comment]
Hi @balazsbotond ! Thank you for your response, again I am a huge fan of urlcat.

> I don't think 1 vs 10 kB matters in any but the most extreme cases.

Part of urlcat's appeal is its great utility in even the most extreme cases. I recognize I am probably in the minority here, but I have enjoyed using it in certain packages where, for one reason or another, the performance budget is extremely tight and every kilobyte matters.

I am happy to hear that 2.x will still be actively maintained and look forward to continue using it for a long time to come.

**Comment by balazsbotond** [comment]
@wescopeland I updated the README to highlight that the 2.x version is still available and actively maintained. Please report any issues you encounter using it!

**Comment by wescopeland** [comment]
> @wescopeland I updated the README to highlight that the 2.x version is still available and actively maintained. Please report any issues you encounter using it!

Thanks again, while I have you here just want to express my gratitude for this package. I use it in at least 10 apps, small and large, and find it extremely practical.
