### ISSUE TITLE
Measure code coverage for TypeScript instead of JavaScript

### ISSUE THREAD

**Issue by balazsbotond** [balazsbotond/urlcat#39]
Our current method for measuring code coverage is rather limited. First, it works on the JavaScript output instead of the original TypeScript; second, it also measures coverage for the tests themselves. The only thing it should measure is `src/index.ts`. The output should be in LCOV format so we can feed it into coveralls.

I have created the current solution in a hurry; I have no time to dig deeper into how TS code coverage measurement works. I would love to learn from someone who is more experienced or simply just has the time to do this properly.

NOTE: please only work on this if you either have experience in this area or are willing to learn about it without much handholding and are able to produce a nice, clean solution.

Thank you!

**Comment by praveen5959** [comment]
Do you mean generating a report of line coverage, branch coverage, etc . We can use jest for that right?

**Comment by balazsbotond** [comment]
We already measure code coverage but the configuration is less than optimal due to the problems I mentioned in the issue description. I don't know jest but it looks like it can generate coverage reports for TypeScript so it might be a good solution.

**Comment by praveen5959** [comment]
So if your case is to generate a coverage HTML report then JEST can do it. I have worked on it also so I can help.
![image](https://user-images.githubusercontent.com/30530587/94789586-b646e300-03f2-11eb-8dc1-fa7e6b725608.png)


P.S. The label should be Hacktoberfest to be counted I guess.

**Comment by balazsbotond** [comment]
An HTML report would be nice but the **LCOV** report is the main thing here, that's what gets fed to coveralls (as you can see in `package.json`).

Oh, I didn't know the label had to be capitalized. I'll rename it, thanks for pointing it out.

**Comment by praveen5959** [comment]
JEST provides LCOV report itself in HTML report.
DOCS reference: https://jestjs.io/docs/en/configuration#coveragereporters-arraystring--string-options

**Comment by balazsbotond** [comment]
Sounds great, thanks!

**Comment by balazsbotond** [comment]
I can't assign this issue to you on my phone but feel free to start working on it.

**Comment by praveen5959** [comment]
Okay then I will start working on it and will keep you updated.

**Comment by praveen5959** [comment]
Hey I checked your test configuration and now I am bit confused. You are already generating coverage in the form of HTML report.

![image](https://user-images.githubusercontent.com/30530587/94804534-991d0f00-0408-11eb-960b-547de5679f8b.png)

So what's the exact issue?

**Comment by balazsbotond** [comment]
The exact issue is described in my first comment [here](https://github.com/balazsbotond/urlcat/issues/39#issue-712572950).

**Comment by praveen5959** [comment]
Oh I think I misunderstood it.
I am sorry.
I think you should keep the issue open so that others can also pitch meanwhile I will try n understand more.
Sorry again.

**Comment by balazsbotond** [comment]
@praveen5959 It's ok, thank you for offering your help and looking into it :)

**Comment by balazsbotond** [comment]
To clarify: this issue is still open and we are still looking for someone who can help.

**Comment by balazsbotond** [comment]
Solved in #44. Closing.
