### ISSUE TITLE
Proofread English text in the README and JSDoc comments

### ISSUE THREAD

**Issue by balazsbotond** [balazsbotond/urlcat#40]
I'm not a native English speaker. I would be very glad if someone from an English-speaking country could review the README and the JSDoc comments and correct any spelling/grammatic/stylistic mistakes.

While we have already received a contribution for this, further ones would be still very much appreciated.

**Comment by withoutwaxaryan** [comment]
Hello there! My English is quite fluent, I can help :)) 
I proofread the README.md , and I didn't find any linguistic errors there, at all :))

Could you please point out what do you mean by JSDoc comments? I could not find it anywhere. 
Thanks!

**Comment by balazsbotond** [comment]
@withoutwaxaryan thank you! I'm glad to hear there are no problems with the README anymore.

You can find the JSDoc comments in this file:
https://github.com/balazsbotond/urlcat/blob/master/src/index.ts

Look for blocks like the following:

```ts
/**
 * Builds a URL using the base template and parameters specified.
 *
 * @param {String} baseTemplate a URL template that contains zero or more :params
 * @param {Object} params an object with properties that correspond to the :params
 *   in the base template. Unused properties become query params.
 *
 * @returns {String} a URL with path params substituted and query params appended
 *
 * @example
 * ```ts
 * urlcat('http://api.example.com/users/:id', { id: 42, search: 'foo' })
 * // -> 'http://api.example.com/users/42?search=foo
 * ```
 */
```

**Comment by withoutwaxaryan** [comment]
Thanks, I found very small errors ( they might not even be errors) . Ill just send a PR, and let you decide :))

**Comment by balazsbotond** [comment]
@withoutwaxaryan thanks a lot! 👍

**Comment by withoutwaxaryan** [comment]
I have sent a PR, the changes look quite trivial, but hopefully, helps :))

**Comment by balazsbotond** [comment]
Thank you, it definitely helps! I've just merged your PR.

**Comment by balazsbotond** [comment]
@all-contributors please add @withoutwaxaryan for docs
