### ISSUE TITLE
Update README to reflect changes in v3

### ISSUE THREAD

**Issue by tcarrio** [balazsbotond/urlcat#56]
**Describe the bug**
The README notes several key features to the project. From the README:

> Features:
> 
>     Friendly API
>     No dependencies
>     0.8 KB minified and gzipped
>     TypeScript types provided

The second and third bullets are no longer correct.

**To Reproduce**
1. Go to README
2. Scroll down to 'Features'
3. See error

**Expected behavior**
The updated information on key features with the latest in master.

**Screenshots**

**Additional context**
This should be updated to the correct minified size and no longer include a mention of zero dependencies.

**Comment by tcarrio** [comment]
Hoping we can figure out a way to get around these issues to continue supporting Deno. While `qs` might be an easier way for the package to support query parameters, it could be difficult to require dependencies and support Deno. We'll probably have to hold further discussion here or open another issue to track it.

**Comment by balazsbotond** [comment]
I think we should keep this issue as a reminder to update the README before releasing the next major version.

I've just opened a new issue to discuss Deno support: #74

**Comment by balazsbotond** [comment]
Fixed in https://github.com/balazsbotond/urlcat/pull/190
