### ISSUE TITLE
Remove duplicate sections from the docs

### ISSUE THREAD

**Issue by EngrKhizarIqbal** [balazsbotond/urlcat#63]
In the [documentation](https://urlcat.dev/), we have a contribute a section on the main page as well as in separate pages. We need to remove either one. I added separate pages so we can add more info on how to contribute or compile from the source and do discuss this were to keep these details? on the main page or on separate pages?

@balazsbotond whats is your opinion on this?

**Comment by balazsbotond** [comment]
@EngrKhizarIqbal good idea! I think we should keep the separate contribution page and remove it from the main page.
